### Numpy

In [10]:
import numpy as np

In [12]:
list1 = [1,2,3,4,5]

In [14]:
x = np.array(list1)

In [15]:
type(x)

numpy.ndarray

In [16]:
np.shape(x)

(5,)

In [17]:
x.shape

(5,)

In [18]:
np.array([2,2,2,2])

array([2, 2, 2, 2])

In [19]:
np.array((3,3,3,3))

array([3, 3, 3, 3])

In [21]:
np.array({1,1,1,1}).shape

()

In [23]:
arr2d = np.array([[1,1,1], [2,2,2], [3,3,3]])

In [24]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [25]:
arr2d.shape

(3, 3)

In [26]:
list1

[1, 2, 3, 4, 5]

In [27]:
list2 = [6,7,8,9,10]

In [28]:
arr2d_2 = np.array([list1, list2])

In [29]:
arr2d_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
arr2d_2.shape

(2, 5)

#### NumPy DataType Objects

In [32]:
100/3

33.333333333333336

In [35]:
np.array([1,2,3.1453,5], dtype=np.longdouble)

array([1.    , 2.    , 3.1453, 5.    ], dtype=float64)

In [36]:
np.array([1,2,3.1453,5], dtype='g')

array([1.    , 2.    , 3.1453, 5.    ], dtype=float64)

#### 56. Array Slicing and Indexing

In [37]:
arr1 = np.array([1,1,1,1])
arr2 = np.array([[1,1,1,1]])

In [38]:
arr1.shape

(4,)

In [39]:
arr2.shape

(1, 4)

#### 56. Slicing and indexing

In [41]:
array_1d = np.array([2,5,6,7,6,4,3])
array_2d = np.array([[2,5,6,7,60,47,3],
                     [11,50,6,9,62,42,30],
                     [16,53,86,69,2,2,50]])

In [42]:
array_1d

array([2, 5, 6, 7, 6, 4, 3])

In [43]:
array_2d

array([[ 2,  5,  6,  7, 60, 47,  3],
       [11, 50,  6,  9, 62, 42, 30],
       [16, 53, 86, 69,  2,  2, 50]])

In [44]:
array_1d[4]

6

In [45]:
array_1d[4:]

array([6, 4, 3])

In [46]:
array_1d[2:6]

array([6, 7, 6, 4])

In [47]:
array_1d[::-1]

array([3, 4, 6, 7, 6, 5, 2])

In [48]:
array_2d[1:,2:]

array([[ 6,  9, 62, 42, 30],
       [86, 69,  2,  2, 50]])

In [49]:
array_2d[2,6]

50

In [50]:
array_2d[::-1]

array([[16, 53, 86, 69,  2,  2, 50],
       [11, 50,  6,  9, 62, 42, 30],
       [ 2,  5,  6,  7, 60, 47,  3]])

In [51]:
array_2d[:,::-1]

array([[ 3, 47, 60,  7,  6,  5,  2],
       [30, 42, 62,  9,  6, 50, 11],
       [50,  2,  2, 69, 86, 53, 16]])

#### Bolean Array Indexing

In [52]:
array_1d

array([2, 5, 6, 7, 6, 4, 3])

In [53]:
array_1d > 3

array([False,  True,  True,  True,  True,  True, False])

In [54]:
array_1d [array_1d>3]

array([5, 6, 7, 6, 4])

In [55]:
array_2d

array([[ 2,  5,  6,  7, 60, 47,  3],
       [11, 50,  6,  9, 62, 42, 30],
       [16, 53, 86, 69,  2,  2, 50]])

In [56]:
array_2d>10

array([[False, False, False, False,  True,  True, False],
       [ True,  True, False, False,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True]])

In [57]:
array_2d[array_2d>10] #one dimensional array

array([60, 47, 11, 50, 62, 42, 30, 16, 53, 86, 69, 50])

In [58]:
array_1 = np.array([1,1,2,3,4])
list_1 = [1,1,2,3,4]

In [59]:
list_1[0] = 10
list_1

[10, 1, 2, 3, 4]

In [ ]:
list_1[:] = 10 #does not work

In [60]:
array_1[:] = 10
array_1

array([10, 10, 10, 10, 10])

### 57. Array Manipulation

In [62]:
array_1d = np.array([1,2,3,4,5,6,4,2,2,1])
array_2d = np.array([[2,3,2,4,6],
                     [5,6,3,2,4]])

In [63]:
array_1d.shape

(10,)

In [64]:
array_2d.shape

(2, 5)

In [66]:
np.reshape(array_1d,(2,5))
#array_1.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 4, 2, 2, 1]])

In [68]:
array_1d

array([1, 2, 3, 4, 5, 6, 4, 2, 2, 1])

In [71]:
#flatten
array_2d

array([[2, 3, 2, 4, 6],
       [5, 6, 3, 2, 4]])

In [72]:
np.ndarray.flatten(array_2d)

array([2, 3, 2, 4, 6, 5, 6, 3, 2, 4])

In [73]:
np.ndarray.flatten(array_2d).shape

(10,)

In [75]:
#Ravel
np.ravel(array_2d)

array([2, 3, 2, 4, 6, 5, 6, 3, 2, 4])

In [90]:
#Concatenate

array_1 = np.array([[1,1,1],[2,2,2]])

array_2 = np.array([[3,3,3],[4,4,4],[5,5,5]])

array_3 = np.array([[3,3],[4,4],[5,5]])

In [91]:
array_1d.shape

(2, 3)

In [92]:
array_2d.shape

(3, 3)

In [93]:
array_3d.shape

(3, 2)

In [94]:
np.concatenate((array_1,array_2), axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [95]:
np.concatenate((array_3,array_2), axis=1) #axis 1 mean a new column added

array([[3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [96]:
array_1

array([[1, 1, 1],
       [2, 2, 2]])

In [98]:
np.transpose(array_1)

array([[1, 2],
       [1, 2],
       [1, 2]])

In [100]:
#array_1.traspose()

In [101]:
array_unsort = np.array([[1,10,3],[2,3,1]])

In [102]:
array_unsort

array([[ 1, 10,  3],
       [ 2,  3,  1]])

In [103]:
np.sort(array_unsort, axis=1)

array([[ 1,  3, 10],
       [ 1,  2,  3]])

In [104]:
np.sort(array_unsort, axis=0)

array([[ 1,  3,  1],
       [ 2, 10,  3]])

### 58.  Aditional Array Creation Functions

In [105]:
np.full((2,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [107]:
np.full((5,5),fill_value=0,dtype=np.longdouble)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float64)

In [108]:
np.full((3,3),5,np.longdouble)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]], dtype=float64)

In [111]:
#Arrange
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [112]:
np.arange(0,12,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [185]:
np.linspace(0,100,num=12).reshape(3,4)

array([[  0.        ,   9.09090909,  18.18181818,  27.27272727],
       [ 36.36363636,  45.45454545,  54.54545455,  63.63636364],
       [ 72.72727273,  81.81818182,  90.90909091, 100.        ]])

In [117]:
np.linspace(0,100,num=25).reshape(5,5)

array([[  0.        ,   4.16666667,   8.33333333,  12.5       ,
         16.66666667],
       [ 20.83333333,  25.        ,  29.16666667,  33.33333333,
         37.5       ],
       [ 41.66666667,  45.83333333,  50.        ,  54.16666667,
         58.33333333],
       [ 62.5       ,  66.66666667,  70.83333333,  75.        ,
         79.16666667],
       [ 83.33333333,  87.5       ,  91.66666667,  95.83333333,
        100.        ]])

In [119]:
np.random.rand(2,5)

array([[0.41747367, 0.53709019, 0.10485611, 0.50758802, 0.17493708],
       [0.3386598 , 0.42981266, 0.13810681, 0.76443399, 0.12634268]])

In [120]:
np.random.randint(-20,20,(3,3))

array([[-16,   2,  10],
       [  2,  19,   6],
       [  9,  -2, -16]])

### 59. Array Arithmetic and Mathematical Functions

In [121]:
array_3

array([[3, 3],
       [4, 4],
       [5, 5]])

In [122]:
array_1 = np.array([[1,2,3,3,3]])

In [126]:
array_2 = np.array([[1,2,3,4,5,5,3,2,4,2,1,2,3,4,5]]).reshape(5,3)

In [131]:
array_3 = np.array([1,2,3,4,5,5,3,2,4,2,1,2,3,4,5]).reshape(3,5)

In [135]:
array_1+array_1

array([[2, 4, 6, 6, 6]])

In [137]:
np.add(array_1,array_1) #two array as max to sum

array([[2, 4, 6, 6, 6]])

In [138]:
array_1

array([[1, 2, 3, 3, 3]])

In [139]:
array_2

array([[1, 2, 3],
       [4, 5, 5],
       [3, 2, 4],
       [2, 1, 2],
       [3, 4, 5]])

In [140]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [141]:
array_1+array_3 #array 1 is add in each row of array3

array([[2, 4, 6, 7, 8],
       [6, 5, 5, 7, 5],
       [2, 4, 6, 7, 8]])

In [142]:
array_3+5

array([[ 6,  7,  8,  9, 10],
       [10,  8,  7,  9,  7],
       [ 6,  7,  8,  9, 10]])

In [144]:
array_1-array_3

array([[ 0,  0,  0, -1, -2],
       [-4, -1,  1, -1,  1],
       [ 0,  0,  0, -1, -2]])

In [145]:
array_1*5

array([[ 5, 10, 15, 15, 15]])

In [146]:
array_3*5

array([[ 5, 10, 15, 20, 25],
       [25, 15, 10, 20, 10],
       [ 5, 10, 15, 20, 25]])

In [148]:
np.sum(array_3)

46

In [149]:
np.sum(array_3, axis=0) #axis 0 sum by column

array([ 7,  7,  8, 12, 12])

In [150]:
np.sum(array_3, axis=1) #axis 1 sum by rows

array([15, 16, 15])

In [152]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [153]:
np.cumsum(array_3, axis=1)

array([[ 1,  3,  6, 10, 15],
       [ 5,  8, 10, 14, 16],
       [ 1,  3,  6, 10, 15]], dtype=int32)

In [154]:
np.cumsum(array_3, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  5,  5,  8,  7],
       [ 7,  7,  8, 12, 12]], dtype=int32)

In [155]:
np.cumsum(array_3)

array([ 1,  3,  6, 10, 15, 20, 23, 25, 29, 31, 32, 34, 37, 41, 46],
      dtype=int32)

In [156]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [158]:
array_3.mean()

3.066666666666667

In [159]:
np.mean(array_3,axis=0)

array([2.33333333, 2.33333333, 2.66666667, 4.        , 4.        ])

In [160]:
np.mean(array_3,axis=1)

array([3. , 3.2, 3. ])

In [162]:
np.amax(array_3, axis=1)

array([5, 5, 5])

In [163]:
np.amin(array_3, axis=0)

array([1, 2, 2, 4, 2])

In [164]:
np.amin(array_3, axis=1)

array([1, 2, 1])

### 60. IO Functions in NumPy

In [187]:
x = np.loadtxt('tfl-daily-cycle-hires.txt',delimiter=',', usecols=(1), skiprows=1)

In [188]:
x

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [189]:
np.count_nonzero(x)

4081

In [190]:
x.max()

73094.0

In [191]:
x.min()

2764.0

In [192]:
x.mean()

26261.932124479295

In [193]:
x.std()

9740.107235227775

In [194]:
x

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [184]:
np.savetxt('test_output.txt',)